EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DB_PATH = "/news_announcements_digest/data/chroma/vector_store.db"
KB_DIR= '/news_announcements_digest/data/knowledge_base'
COLLECTION_NAME = "news_items"
TOP_K = 5
MAX_RETRIES = 3
CHUNK_SIZE = 300
CHUNK_OVERLAP = 30
DEDUP_THRESHOLD = 0.92
MAX_CHARS_BEFORE_SPLIT=1500
MAX_REPAIR_ATTEMPTS = 2
DEFAULT_MODEL = "llama-3.3-70b-versatile"
DEFAULT_TEMPERATURE = 0.2
MAX_CRITIC_ATTEMPTS = 2