[project]
name = "news-announcements-digest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.3.16",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.11",
    "llama-index>=0.14.23",
    "llama-index-core>=0.14.23",
    "llama-index-embeddings-huggingface>=0.7.0",
    "llama-index-vector-stores-chroma>=0.5.5",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "streamlit>=1.62.0",
]
